// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4980.ParadeBot;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.CANTalon;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static CANTalon driveBaserightRearMotor;
    public static CANTalon driveBaseleftRearMotor;
    public static CANTalon driveBaserightFrontMotor;
    public static CANTalon driveBaseleftFrontMotor;
    public static CANTalon driveBaseshooterMotor;
    public static CANTalon driveBasenoisyMotor;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveBaserightRearMotor = new CANTalon(0);
        LiveWindow.addActuator("driveBase", "rightRearMotor", driveBaserightRearMotor);
        
        driveBaseleftRearMotor = new CANTalon(1);
        LiveWindow.addActuator("driveBase", "leftRearMotor", driveBaseleftRearMotor);
        
        driveBaserightFrontMotor = new CANTalon(3);
        LiveWindow.addActuator("driveBase", "rightFrontMotor", driveBaserightFrontMotor);
        
        driveBaseleftFrontMotor = new CANTalon(2);
        LiveWindow.addActuator("driveBase", "leftFrontMotor", driveBaseleftFrontMotor);
        
        driveBaseshooterMotor = new CANTalon(4);
        LiveWindow.addActuator("driveBase", "shooterMotor", driveBaseshooterMotor);
        
        driveBasenoisyMotor = new CANTalon(5);
        LiveWindow.addActuator("driveBase", "noisyMotor", driveBasenoisyMotor);
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
