// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4980.ParadeBot.subsystems;

import org.usfirst.frc4980.ParadeBot.Robot;
import org.usfirst.frc4980.ParadeBot.RobotMap;
import org.usfirst.frc4980.ParadeBot.commands.*;
import edu.wpi.first.wpilibj.CANTalon;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class driveBase extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final CANTalon rightRearMotor = RobotMap.driveBaserightRearMotor;
    private final CANTalon leftRearMotor = RobotMap.driveBaseleftRearMotor;
    private final CANTalon rightFrontMotor = RobotMap.driveBaserightFrontMotor;
    private final CANTalon leftFrontMotor = RobotMap.driveBaseleftFrontMotor;
    private final CANTalon shooterMotor = RobotMap.driveBaseshooterMotor;
    private final CANTalon noisyMotor = RobotMap.driveBasenoisyMotor;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        setDefaultCommand(new tankDrive());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
   public void Drive() {
	   double left = Robot.oi.xboxController.getRawAxis(1);
	   double right = Robot.oi.xboxController.getRawAxis(5);
	   leftFrontMotor.set(left);
	   rightFrontMotor.set(right);
	   leftRearMotor.set(left);
	   rightRearMotor.set(right);
	   
	   
	   
   }
}

